### ISSUE TITLE
feature request: use standard aws cli config

### ISSUE THREAD

**Issue by thomasklinger1234** [otto-de/logsmith#1]
# Description 

Currently, I need to maintain a separate configuration file for logsmith. It would be awesome to use the standard AWS CLI configuration in `$HOME/.aws/config`.

**Comment by redvox** [comment]
Hi @thomasklinger1234, thank you for your feature request.
As of now the logsmith uses `.aws/config` to set the region concurrently to the login loop.

We could store the logsmith configuration in the config file, which would mean moving the logsmith-config-file format from yaml to INI file instead.
Also the combination of multiple profiles will be somewhat harder, because INI files do not support subsections. Of course we can do something like `[SECTION1-SUBSECTION1]` but i don't know if it will be very readable.

The main reason why I would like to keep both configs separated is, first because they are both very different things and second to avoid accidental overwriting aws service configuration (like s3).

If you have ideas how to combine the two configs without problems and maintaining the ease of the current yaml configuration i'm more than glad to hear your thoughts.
